#!/usr/bin/env bash
set -euo pipefail

# find script dir and ensure PWD is the repo root
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
repo_root=$(cd "$script_dir/.." && pwd -P)
cd "$repo_root"

# Create config dir if not present
if [[ ! -d "${repo_root}/config" ]]; then
    mkdir -p "${repo_root}/config"
    hass --config "${repo_root}/config" --script ensure_config
fi

# Set the path to custom_components
## This let's us have the structure we want <root>/custom_components/rainforest_eagle3
## while at the same time have Home Assistant configuration inside <root>/config
## without resulting to symlinks.
# if [[ -z "${PYTHONPATH:-}" ]]; then
#     export PYTHONPATH="${repo_root}/custom_components"
# else
#     export PYTHONPATH="${PYTHONPATH}:${repo_root}/custom_components"
# fi

# symlink
if [[ ! -L "${repo_root}/config/custom_components/rainforest_eagle3" ]]; then
    mkdir -p "${repo_root}/config/custom_components"
    ln -sf "${repo_root}/custom_components/rainforest_eagle3" "${repo_root}/config/custom_components/rainforest_eagle3"
fi

# Start Home Assistant
exec hass --config "${repo_root}/config" --debug
