#!/usr/bin/env bash
set -euo pipefail

# find script dir and ensure PWD is the repo root
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
cd "$script_dir/.."

ruff check --select I --fix .
ruff format
ruff check --fix
