#!/usr/bin/env bash
set -euo pipefail

# find script dir and ensure PWD is the repo root
script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
cd "$script_dir/.."

if [[ (! -d ".venv") && (-z "${VIRTUAL_ENV:-}") ]]; then
    echo "Creating virtual environment with uv..."
    uv venv .venv --python python3.13 --seed
    uv pip install -U pip setuptools wheel packaging
fi

uv pip install --editable '.[dev]'

echo "Setup complete. To activate the virtual environment, run:"
echo "  source .venv/bin/activate"
echo "Then you can start Home Assistant with:"
echo "  ./scripts/develop"
