#!/usr/bin/env bash
# Push custom component folder to an rclone ssh remote for testing.
set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <rclone-remote> [rclone-flags]" >&2
    echo "Example: $0 myhassio-ssh" >&2
    exit 1
fi
rclone_remote=$1
shift

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
cd "${script_dir}/.."
if [[ $? -ne 0 ]]; then
    echo "Could not change to script directory ${script_dir}" >&2
    exit 1
fi

rclone_flags=(
    "--progress"
    --exclude '.git/**'
    --exclude '**/__pycache__/'
    --exclude '*.pyc'
)

# actually perform the sync
rclone sync \
    ./custom_components/rainforest_eagle3 \
    "${rclone_remote}:/config/custom_components/rainforest_eagle3" \
    "${rclone_flags[@]}" "$@"
